# Generated by Django 5.1.3 on 2024-11-14 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('reader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.reader')),
            ],
        ),
    ]
