# Generated by Django 5.1.3 on 2024-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_reader_id_loan_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
